# Generated by Django 2.0 on 2017-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150,blank=True, null=True)),
                ('author', models.CharField(max_length=150,blank=True, null=True)),
                ('data_published', models.DateField(blank=True, null=True)),
                ('number_of_page', models.IntegerField(blank=True, null=True)),
                ('type_of_book', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
